#!/usr/bin/env python3
"""
Makes deploys fast and reliable by shipping trained artifacts instead of
training on every deploy.

Before: every Render deploy downloaded two datasets and trained two models
        (12-16 min, fails on free-tier memory/timeouts).
After:  deploy = pip install + start (~2 min, no network, no training).

Run from repo root, AFTER training locally so the artifacts exist:
    python3 vendor_artifacts.py
"""
from pathlib import Path
import sys

root = Path.cwd()
models = root / "backend/app/models"
data = root / "backend/app/data"

# --- safety check: refuse to run without artifacts ---
required = ["text_classifier.joblib", "text_vectorizer.joblib",
            "transaction_model.joblib", "transaction_scaler.joblib",
            "transaction_features.joblib"]
missing = [f for f in required if not (models / f).exists()]
if missing:
    sys.exit(f"ERROR: missing artifacts: {missing}\n"
             f"Train first:\n"
             f"  cd backend && python app/ml/download_dataset.py\n"
             f"  python app/ml/train_text_classifier.py\n"
             f"  python app/ml/train_transaction_model.py")

changed = []

# --- 1. .gitignore: stop excluding the artifacts we now want committed ---
p = root / ".gitignore"
t = p.read_text()
t = t.replace(
    "# Model artifacts (regenerate with train scripts - large binary files don't belong in git history)\nbackend/app/models/*.joblib\n",
    "# Model artifacts ARE committed (~3.5MB total). Deploys install and start rather\n"
    "# than training, which keeps them fast and removes a network dependency at build\n"
    "# time. Retrain with the scripts in app/ml/ and commit the updated files.\n")
t = t.replace(
    "# Data (raw dataset is downloaded by setup script, synthetic data is regenerated by training)\nbackend/app/data/*.csv\n",
    "# Datasets ARE committed (~1.6MB total) so training is reproducible and the build\n"
    "# does not depend on third-party mirrors staying online.\n")
p.write_text(t)
changed.append(".gitignore: un-ignore models and data")

# --- 2. build.sh: stop training on deploy ---
p = root / "backend/build.sh"
p.write_text('''#!/usr/bin/env bash
set -e

# Trained models and datasets are committed to the repo, so a deploy only needs
# to install dependencies. Training on every deploy was slow (12-16 min) and
# fragile: it depended on two third-party dataset mirrors staying online and hit
# free-tier memory limits during scikit-learn training.
#
# To update the models, retrain locally and commit the new artifacts:
#   python app/ml/download_dataset.py
#   python app/ml/train_text_classifier.py
#   python app/ml/train_transaction_model.py
pip install -r requirements.txt
''')
changed.append("build.sh: install only, no training")

print("\n".join(f"  [ok] {c}" for c in changed))
print("\nNow run:")
print("  git add -A && git status      # expect .joblib + .csv files as NEW")
print("  git commit -m 'Ship trained artifacts; deploys no longer train'")
print("  git push")
